export SHELL=/usr/bin/gnome-terminal
export QT_STYLE_OVERRIDE=GTK+
export ANKI_BASE="$XDG_DATA_HOME/anki"
export GIMP2_DIRECTORY="$XDG_CONFIG_HOME/gimp"
export GTK_RC_FILES="$XDG_CONFIG_HOME/gtk-1.0/gtkrc"
"export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc""
