#!/usr/bin/perl
# Abandoned because there aren't enough icons to distinguish...

use strict;
use warnings;
use utf8;
use open ':std', ':encoding(UTF-8)';

my $volume;
my $mute;
my $icon;

open(AMIXER, "amixer get Master | grep -Po '[0-9]+%' |") or die;
$volume = <AMIXER>;
